export const GET_CHARACTER_ITEMS_PENDING = 'GET_CHARACTER_ITEMS_PENDING';
export const GET_CHARACTER_ITEMS_FULFILLED = 'GET_CHARACTER_ITEMS_FULFILLED';
export const GET_CHARACTER_ITEMS_REJECTED = 'GET_CHARACTER_ITEMS_REJECTED';