export const GET_EPISODE_ITEMS_PENDING = 'GET_EPISODE_ITEMS_PENDING';
export const GET_EPISODE_ITEMS_FULFILLED = 'GET_EPISODE_ITEMS_FULFILLED';
export const GET_EPISODE_ITEMS_REJECTED = 'GET_EPISODE_ITEMS_REJECTED';