export const GET_LOCATION_ITEMS_PENDING = 'GET_LOCATION_ITEMS_PENDING';
export const GET_LOCATION_ITEMS_FULFILLED = 'GET_LOCATION_ITEMS_FULFILLED';
export const GET_LOCATION_ITEMS_REJECTED = 'GET_LOCATION_ITEMS_REJECTED';